version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=redmine
      - MARIADB_USER=redmine
      - MARIADB_DATABASE=redmine
      - MARIADB_PASSWORD=redmine
    volumes:
      - 'mariadb_data:/var/lib/mysql'
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
      - REDMINE_PLUGINS_MIGRATE=1
    ports:
      - '80:3000'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
